### PR TITLE
Fieldmapupdate

### PR DESCRIPTION
**Pull request by slin63**
#### Changes to the field map generator:

1. Maps are now color coded by experiment
2. Maps now support multiple fields and will generate new worksheets appropriately
3. "Generate by field" buttons added to plot-data browsers

### CODE REVIEW

**Comment by nickmorales** [comment]
Hi Shean,

I'm glad that you are making progress with the database. Can you please
merge those pull requests with the master branch of the
nelsonlab/django_NelsonDB repo?

Thanks,
Nick

**Comment by slin63** [comment]
Hey Nick,

Most of the changes I've made are just small changes to the original models
or other things that needed to be adjusted for usage by Santiago's lab. For
the most part the only differences between the two repos are different
model usage and a small handful of lab-specific features. Is there anything
you're particularly interested in?

Best,
Shean

**Comment by nickmorales** [comment]
Ok, well I'm interested in
Changes to the field map generator:

   1. Maps are now color coded by experiment
   2. Maps now support multiple fields and will generate new worksheets
   appropriately
   3. "Generate by field" buttons added to plot-data browsers


Sounds very interesting.

**Comment by slin63** [comment]
Sure thing. I've made changes to the Row model (added a row_number
property) so now there's a complete row/range coordinate. The FieldMapper
generates field maps for selected experiments or fields based on this
coordinate data.

Here's <https://github.com/slin63/Dump-Scrape/tree/master/mapgen/online_gen> an
older version of the mapper that may or may not work anymore. There's a
whole host of functions and other things that go with it on the website
that I can send you tomorrow (not at my machine right now).

Attached below is an example output.

Best,
Shean

**Pull request closed without merging**
